['a bordo', 1.5]
['com admiracao', 1.5]
['muito adoravel', 1.5]
['com raiva', 1.5]
['tudo bem', 1.5]
['pedir desculpas', 1.5]
['pediu desculpa', 1.5]
['pede desculpas', 1.5]
['vale a pena', 1.5]
['de ativos', 1.5]
['com certeza', 1.5]
['mais lindo', 1.5]
['mais bonita', 1.5]
['beneficio eclesiastico', 1.5]
['responsabilidade social', 1.5]
['sem culpa', 1.5]
['muito ousado', 1.5]
['mais ousado', 1.5]
['muito entediado', -2.5]
['muito entediados', -2.5]
['mais forte', 1.5]
['mais valente', 1.5]
['tirar o folego', 1.5]
['mais brilhante', 1.5]
['mais calmo', 1.5]
['se preocupa', 1.5]
['a comemorar', 1.5]
['sem paciencia', 1.5]
['instituicoes de caridade', 1.5]
['mais charmoso', 1.5]
['cheio de alegria', 1.5]
['mais alegre', 1.5]
['lider de torcida', 1.5]
['lideres de torcida', 1.5]
['mais inteligente', 1.5]
['venha fazer', 1.5]
['com conforto', 1.5]
['com confianca', 1.5]
['de forma convincente', 1.5]
['processo judicial', 1.5]
['processos judiciais', 1.5]
['com credibilidade', 1.5]
['mais bonito', 1.5]
['de forma defensiva', 1.5]
['dias uteis', 1.5]
['sem duvida', 1.5]
['falta de duvida', 1.5]
['alta tensao', -1.5]
['falta de', -1.5]
['bolinho de massa', 1.5]
['com facilidade', 1.5]
['mais facil', 1.5]
['se empenhar', 1.5]
['com entusiasmo', 1.5]
['se destacou', 1.5]
['se destaca', 1.5]
['falta de exaustao', 1.5]
['se expande', 1.5]
['se estende', 1.5]
['sem falhas', 1.5]
['falta de falhas', 1.5]
['sem medo', 1.5]
['frequentadores do festival', 1.5]
['em forma', 1.5]
['de forma lisonjeira', 1.5]
['com flexibilidade', 1.5]
['mais flirti', 1.5]
['com carinho', 1.5]
['mais tolo', 1.5]
['baseado em livre', 1.5]
['bases livres', 1.5]
['bordo livre', 1.5]
['livre nascido', 1.5]
['forma livre', 1.5]
['maos livres', 1.5]
['terras livres', 1.5]
['trabalhador autonomo', 1.5]
['trabalho autonomo', 1.5]
['mais livre', 1.5]
['estilo livre', 1.5]
['pensador livre', 1.5]
['roda livre', 1.5]
['rodas livres', 1.5]
['livre arbitrio', 1.5]
['escrita livre', 1.5]
['mais amigaveis', 1.5]
['muito amigos', 1.5]
['sem fumo', 1.5]
['mais divertido', 1.5]
['mais engracado', 1.5]
['de maneira engracada', 1.5]
['homem engracado', 1.5]
['homens engracados', 1.5]
['mais geek', 1.5]
['mais suave', 1.5]
['mais gentil', 1.5]
['com prazer', 1.5]
['entrega de deus', 1.5]
['mais gracioso', 1.5]
['com gratidao', 1.5]
['mais esperto', 1.5]
['falta de culpa', 1.5]
['mais feliz', 1.5]
['mais celestial', 1.5]
['para o ceu', 1.5]
['de forma util', 1.5]
['mais honesto', 1.5]
['na esperanca', 1.5]
['fazendo graca', 1.5]
['sem ferida', 1.5]
['de forma inspiradora', 1.5]
['muito inteligente', 1.5]
['com alegria', 1.5]
['de alegria', 1.5]
['controle de video game', 1.5]
['mais intenso', 1.5]
['do tipo', 1.5]
['se beijando', 1.5]
['mais animado', 1.5]
['meios de subsistencia', 1.5]
['viver muito', 1.5]
['rindo muito', 1.5]
['ri muito', 1.5]
['o amor e', 1.5]
['com sorte', 1.5]
['mais afortunado', 1.5]
['nada mal', 2.5]
['mais sortudas', 1.5]
['por sorte', 1.5]
['mais limpo', 1.5]
['mais puro', 1.5]
['mais nitido', 1.5]
['mais legal', 1.5]
['esta bem', 1.5]
['uma vez na vida', 1.5]
['muito feliz', 1.5]
['simplifica demais', 1.5]
['sem dor', 1.5]
['falta de dor', 1.5]
['para provar', 1.5]
['em panico', 1.5]
['flor da paixao', 1.5]
['mais tranquilo', 1.5]
['manutencao da paz', 1.5]
['tempo de paz', 1.5]
['tempos de paz', 1.5]
['mais perfeito', 1.5]
['mais prazeroso', 1.5]
['mais agradavel', 1.5]
['por favor', 1.5]
['mais positivista', 1.5]
['sem pressao', 1.5]
['combate de premios', 1.5]
['vencedor do premio', 1.5]
['de lucro', 1.5]
['de forma promissora', 1.5]
['mais orgulhoso', 1.5]
['se alegrou', 1.5]
['se alegra', 1.5]
['muito ricos', 1.5]
['mais rico', 1.5]
['sem risco', 1.5]
['luz de seguranca', 1.5]
['luzes de seguranca', 1.5]
['com seguranca', 1.5]
['mais segura', 1.5]
['mais seguro', 1.5]
['homem de seguranca', 1.5]
['de forma satisfatoria', 1.5]
['salve ', 1.5]
['chave de fenda', 1.5]
['chaves de fenda', 1.5]
['semelhante a um parafuso', 1.5]
['de forma segura', 1.5]
['deixar seguro', 1.5]
['tornar seguro', 1.5]
['a prova de choque', 1.5]
['mais sincero', 1.5]
['mais liso', 1.5]
['alma gemea', 1.5]
['mais furtivo', 1.5]
['sem stress', 1.5]
['falta de estresse', 1.5]
['caixa forte', 1.5]
['caixas fortes', 1.5]
['homem forte', 1.5]
['homens fortes', 1.5]
['ter sucesso', 1.5]
['bem sucedido', 1.5]
['com exito', 1.5]
['mais ensolarado', 1.5]
['brilho do sol', 1.5]
['sol brilhante', 1.5]
['apoio suporte', 1.5]
['de suporte', 1.5]
['mais supremo', 1.5]
['colher de cha', 1.5]
['colheres de cha', 1.5]
['mais terno', 1.5]
['se amolece', 1.5]
['sem tensao', 1.5]
['sem terror', 1.5]
['mais agradecido', 1.5]
['solucionar problemas', 1.5]
['solucionador de problemas', 1.5]
['solucionadores de problemas', 1.5]
['solucao de problemas', 1.5]
['mais verdadeiro', 1.5]
['mais confiavel', 1.5]
['para confiar', 1.5]
['passa confianca', 1.5]
['objetos de valor', 1.5]
['de valor', 1.5]
['sem vicios', 1.5]
['sinais vitais', 1.5]
['de sangue quente', 1.5]
['mais quente', 1.5]
['calor caloroso', 1.5]
['bem vinda', 1.5]
['bem vindo', 1.5]
['boa cabeca', 1.5]
['boa fe', 1.5]
['cabecas de poco', 1.5]
['bem estar', 1.5]
['local do poco', 1.5]
['possivel de vencer', 1.5]
['de forma vencedora', 1.5]
['caras espertos', 1.5]
['super inteligente', 1.5]
['mais sabio', 1.5]
['mulheres inteligentes', 1.5]
['nao perde em nada', 2.5]
['nao perde', 2.5]
['com agitacao', -1.5]
['sem forma', -1.5]
['muito irritado', -1.5]
['mais angustiado', -1.5]
['de forma antagonica', -1.5]
['de forma apatica', -1.5]
['muito mal', -3.5]
['pedindo desculpas', -1.5]
['com vergonha', -1.5]
['campo de batalha', -1.5]
['campeao de reclamacao', -1.5]
['campeao de reclamacoes', -1.5]
['campeoes de reclamacoes', -1.5]
['campos de batalha', -1.5]
['frente de batalha', -1.5]
['frentes de batalha', -1.5]
['navio de guerra', -1.5]
['navios de guerra', -1.5]
['caminho de guerra', -1.5]
['vagoes de batalha', -1.5]
['mais bravo', -1.5]
['mais brando', -1.5]
['mais amargo', -1.5]
['lavagem cerebral', -1.5]
['assedio moral', -1.5]
['nao suporto', -1.5]
['sem charme', -1.5]
['sem graca', -1.5]
['sem nocao', -1.5]
['sem conforto', -1.5]
['com compaixao', -1.5]
['sem compaixao', -1.5]
['mais louco', -1.5]
['mais grosseiro', -1.5]
['em bruto', -1.5]
['mais grosso', -1.5]
['mais cruel', -1.5]
['a paixao subita', -1.5]
['mais dificil', -1.5]
['mais escuro', -1.5]
['mais caro', -1.5]
['muito caro', -2.5]
['de forma defeituosa', -1.5]
['mais sujo', -1.5]
['nao acredite', -1.5]
['com nojo', -1.5]
['com desgosto', -1.5]
['nao inclinado', -1.5]
['nao gosta', -1.5]
['nao gostei', -1.5]
['com angustia', -1.5]
['com desconfianca', -1.5]
['se afoga', -1.5]
['mais aborrecido', -1.5]
['mais burro', -1.5]
['mais tonto', -1.5]
['deposito de lixo', -1.5]
['lata de lixo', -1.5]
['mais vazio', -1.5]
['de forma vazia', -1.5]
['mais malvado', -1.5]
['muito mau', -2.5]
['terrivelmente mau', -1.5]
['sem fe', -1.5]
['deteccao de avarias', -1.5]
['mais danificado', -1.5]
['pode falhar', -1.5]
['falta de responsabilidade', -1.5]
['com medo', -1.5]
['mais terrivel', -1.5]
['mais entusiasmado', -1.5]
['mais foolhardier', -1.5]
['mais fofo', -1.5]
['em tonturas', -1.5]
['base livre', -1.5]
['amigo sem amigos', -1.5]
['franzindo a testa', -1.5]
['cabeca de foda', -1.5]
['muito parecido', -1.5]
['muito geek', -1.5]
['sem glamour', -1.5]
['mais sombrio', -1.5]
['sem cascas', -1.5]
['mais grave', -1.5]
['lavagem ecologica', -1.5]
['fez uma careta', -1.5]
['fazendo caretas', -1.5]
['mais grimmest', -1.5]
['mais mal humorado', -1.5]
['mais culpado', -1.5]
['com culpa', -1.5]
['arma de fogo', -1.5]
['mais duro', -1.5]
['mais severo', -1.5]
['destruidor de coracoes', -1.5]
['coracao partido', -1.5]
['sem coracao', -1.5]
['falta de coracao', -1.5]
['se escondendo', -1.5]
['com saudades de casa', -1.5]
['sem esperanca', -1.5]
['sem humor', -1.5]
['falta de humor', -1.5]
['com humor', -1.5]
['se precipitou', -1.5]
['se precipita', -1.5]
['se precipitando', -1.5]
['eu vou', -1.5]
['na duvida', -1.5]
['com ciumes', -1.5]
['sem alegria', -1.5]
['falta de alegria', -1.5]
['acao judicial', -1.5]
['acoes judiciais', -1.5]
['mais preguicoso', -1.5]
['mais lazyest', -1.5]
['mais solitario', -1.5]
['muito sozinho', -1.5]
['totalmente sozinho', -1.5]
['estar sozinho', -1.5]
['com perdas', -1.5]
['mais lousier', -1.5]
['mais pessimo', -1.5]
['bola baixa', -1.5]
['baixo nascido', -1.5]
['de baixo teor', -1.5]
['mais baixo', -1.5]
['em minuscula', -1.5]
['menor classe', -1.5]
['baixa vida', -1.5]
['luz baixa', -1.5]
['a espreita', -1.5]
['de forma maniaca', -1.5]
['sem significado', -1.5]
['com melancolia', -1.5]
['sem sentido', -1.5]
['comportar-se mal', -1.5]
['mal comportado', -1.5]
['mal interpretado', -1.5]
['notificacao incorreta', -1.5]
['sente falta', -1.5]
['ausencia de', -1.5]
['por engano', -1.5]
['mal entendido', -1.5]
['entende mal', -1.5]
['mais mau', -1.5]
['mau humor', -1.5]
['filho da puta', -1.5]
['filho duma puta', -1.5]
['de luto', -1.5]
['mais nautico', -1.5]
['mais desagradavel', -1.5]
['mais nerdier', -1.5]
['de forma obsessiva', -1.5]
['sem opcao', -1.5]
['ultrajante, ultrajoso', -1.5]
['reagir exageradamente', -1.5]
['reagido exageradamente', -1.5]
['reacao exagerada', -1.5]
['simplificacao excessiva', -1.5]
['excesso de peso', -1.5]
['causa dor', -1.5]
['entrou em panico', -1.5]
['entrando em panico', -1.5]
['sem paixao', -1.5]
['mais pequeno', -1.5]
['com pena', -1.5]
['mais pitifullest', -1.5]
['sem estimulo', -1.5]
['mais pobre', -1.5]
['faz de conta', -1.5]
['mais precoce', -1.5]
['mais picado', -1.5]
['combate de premio', -1.5]
['combatentes de premios', -1.5]
['sem lucro', -1.5]
['erupcao cutanea', -1.5]
['com remorso', -1.5]
['sem remorsos', -1.5]
['sem remorso', -1.5]
['falta de remorso', -1.5]
['se ressentiu', -1.5]
['com ressentimento', -1.5]
['se ressente', -1.5]
['pedido de demissao', -1.5]
['sem descanso', -1.5]
['se vingaram', -1.5]
['mais arriscado', -1.5]
['deixa a desejar', -1.5]
['de forma arriscada', -1.5]
['mais rude', -1.5]
['muito triste', -2.5]
['muito pouco', -2.5]
['mais triste', -1.5]
['bode expiatorio', -1.5]
['bodes expiatorios', -1.5]
['bolas de parafusos', -1.5]
['mais maluco', -1.5]
['a serio', -1.5]
['mais tremula', -1.5]
['mais agitado', -1.5]
['cabeca de merda', -1.5]
['mais fofa', -1.5]
['com ceptica', -1.5]
['mais sluttier', -1.5]
['mais excitante', -1.5]
['ficando esperto', -1.5]
['sem brincadeira', -1.5]
['poluicao atmosferica', -1.5]
['se achando', -1.5]
['mais esnobe', -1.5]
['se acha', -1.5]
['com tristeza', -1.5]
['fazendo spam', -1.5]
['sem espirito', -1.5]
['apesar de', -1.5]
['de sobressalto', -1.5]
['morrer de fome', -1.5]
['morrendo de fome', -1.5]
['insetos fedorentos', -1.5]
['mais fedido', -1.5]
['cheira mal', -1.5]
['mais persistente', -1.5]
['mais impressionante', -1.5]
['mais estupido', -1.5]
['uma merda', -1.5]
['nao presta', -1.5]
['sem talento', -1.5]
['terno firme', -1.5]
['mais tenso', -1.5]
['muito tenso', -2.5]
['mais timido', -1.5]
['muito timido', -2.5]
['mais complicado', -1.5]
['com problemas', -1.5]
['causador de problemas', -1.5]
['de forma problematica', -1.5]
['sem confianca', -1.5]
['mais feio', -2.5]
['mais feia', -2.5]
['muito feio', -2.5]
['falta de beleza', -1.5]
['nao apreciado', -1.5]
['pouco atraente', -1.5]
['pouco feliz', -3.5]
['um pouco feliz', 1.0]
['pouco triste', 3.5]
['um pouco triste', -2.5]
['nao esta claro', -1.5]
['pegar fogo', -1.5]
['nao confirmado', -1.5]
['nao convencido', -1.5]
['nao credenciado', -1.5]
['nao merecedor', -1.5]
['nao cumprido', -1.5]
['mais infeliz', -2.5]
['pouco saudavel', -1.5]
['sem importancia', -1.5]
['nao impressionado', -1.5]
['nao impressionante', -1.5]
['nao envolvido', -1.5]
['nao amavel', -1.5]
['mal amada', -1.5]
['mal amado', -1.5]
['mal avaliado', -1.5]
['mal avaliados', -1.5]
['mal avaliada', -1.5]
['mal avaliadas', -1.5]
['mais lindos', -1.5]
['nao amor', -1.5]
['nao profissional', -1.5]
['sem garantia', -1.5]
['pouco sofisticado', -1.5]
['mal sucedido', -1.5]
['nao suportado', -1.5]
['com dificuldade', -1.5]
['sem utilidade', -1.5]
['muito vicioso', -1.5]
['sem virtude', -1.5]
['ir embora', -1.5]
['em guerra', -1.5]
['mais fraco', -1.5]
['peixe fraco', -1.5]
['coracao fraco', -1.5]
['lado fraco', -1.5]
['mais chorado', -1.5]
['muito estranho', -2.5]
['mais estranho', -2.5]
['poco de poco', -1.5]
['mais perverso', -1.5]
['nao resistiu', -1.5]
['mau humorado', -1.5]
['nao deu', -1.5]
['nao houve resposta', -1.5]
['maiores baixas', -1.5]
['caiu feio', -1.5]
['cairam feio', -1.5]
['tao absurda', -1.5]
['muito absurda', -2.5]
['nao e simples', -1.5]
['fechou no vermelho', -1.5]
['tapar buraco', -1.5]
['tapacao de buraco', -1.5]
['rombo no orcamento', -1.5]
['nao chegam a acordo', -1.5]
['nao houve acordo', -1.5]
['sem acordo', -1.5]
['nao conseguiram', -2.5]
['nao ha', -2.5]
['nao tem', -2.5]
['nao tiveram', -2.5]
['nao terao', -2.5]
['nao tera', -2.5]
['bandidos explodem', -2.5]
['nao teriam', -2.5]
['nao havera', -2.5]
['nao houve', -2.5]
['bem abaixo', -2.5]
['reajuste de preco', -1.5]
['reajustaram o preco', -1.5]
['anuncia a chegada', 1.5]
['para conscientizar', 1.5]
['amplia restricoes', -1.5]
['toque de recolher', -1.5]
['impedidos de funcionar', -1.5]
['impedido de funcionar', -1.5]
['expressamente vedada',  -1.5]
['expressamente proibida ', -1.5]
['sob pena de', -1.5]
['mais caros', -1.5]
['mais baratos', 1.5]
['salto na produção', 1.5]
['evitar propagacao', 1.5]
['reforcam cuidados', 1.5]
['pelo menos', 1.5]
['forte aliado', 1.5]
['nao chegam a', -1.5]
['a maior', 1.5]
['uma das maiores', 1.5]
['ataques ciberneticos', -1.5]
['esperamos bastante', 1.5]
['alto escalao', 1.5]
['nao entregou', -1.5]
['reparar os danos', 1.5]
['mais queixas', -1.5]
['mais reclamadas', -1.5]
['mais reclamacoes', -1.5]
['com reclamacoes', -1.5]
['mais registros de reclamacao', -1.5]
['mau atendimento', -1.5]
['barrar venda', -1.5]
['forte valorizacao', 1.5]
['danos coletivos', -1.5]
['pouco aproveitados', -1.5]
['sinal verde', 1.5]
['sinal vermelho', -1.5]
['melhor avaliacao', 2.5]
['acendeu o alerta', -1.5]
['parceria entre', 1.5]
['da aval', 1.5]
['dar aval', 1.5]
['deu aval', 1.5]
['lucro liquido', 1.5]
['alta de', 1.5]
['abre investigacao', 1.5]
['abre investigacoes', 1.5]
['abriu investigacoes', 1.5]
['sem sucesso', -1.8]
['com sucesso', -1.8]
['negocio fechado', 1.0]
['negocios fechados', 1.0]
['fechar negocio', 1.0]
['fecham negocio', 1.0]
['tracam planos', 1.0]
['traca plano', 1.0]
['fora do ar', -1.0]
['tracam plano', 1.0]
['planos tracados', 1.0]
['plano tracado', 1.0]
['expande cobertura', 1.0]
['expandem cobertura', 1.0]
['expandir cobertura', 1.0]
['expandir a cobertura', 1.0]
['expandiu cobertura', 1.0]
['expandiu a cobertura', 1.0]
['destino viavel', 1.0]
['destinos viaveis', 1.0]
['acarretar aumentos', -1.5]
['acarretar aumento', -1.5]
['acarretam aumento', -1.5]
['acarretam aumentos', -1.5]
['acarretou em aumentos', -1.5]
['acarretou em aumento', -1.5]
['sem concorrencia', 2.5]
['sem concorrentes', 2.5]
['sem concorrente', 2.5]
['nao acatou', -1.5]
['avanco tecnologico', 1.5]
['avancos tecnologicos', 1.5]
['saia justa', -1.6]
['saude mental', 1.0]
['boas praticas', 1.0]
['boa pratica', 1.0]
['cursos gratuitos', 1.0]
['curso gratuito', 1.0]
['mais geram reclamacao', -2.5]
['menos geram reclamacao', 2.5]
['risco a', -1.5]
['risco as', -1.5]
['risco ao', -1.5]
['risco aos', -1.5]
['diminuir preco', 1.5]
['diminuir precos', 1.5]
['diminuicao de precos', 1.5]
['diminuicao de preco', 1.5]
['aumento de preco', 1.5]
['aumento de precos', 1.5]
['aumentar preco', 1.5]
['aumentar precos', 1.5]
['pior avaliacao', -3.5]
['piores avaliacoes', -3.5]
['piores aspectos', -3.5]
['piores resultados', -3.5]
['pior aspecto', -3.5]
['pior resultado', -3.5]
['melhor avaliacao', 2.5]
['melhores avaliacoes', 2.5]
['mais baratas', 2.5]
['mais barata', 2.5]
['mais caras', -2.5]
['mais cara', -2.5]
['procon notifica', -2.5]
['danos causados', -2.5]
['reparar danos', -2.5]
['da desconto', 1.8]
['dar desconto', 1.8]
['deu desconto', 1.8]
['da descontos', 1.8]
['dar descontos', 1.8]
['deu descontos', 1.8]
['nao entregou', -2.0]
['nao entregaram', -2.0]
['nao resolveu', -2.0]
['nao resolvido', -2.0]
['nao resolvidos', -2.0]
['nao resolvida', -2.0]
['nao resolvidas', -2.0]
['nao e', -2.0]
['nao existe', -2.0]
['nao existem', -2.0]
['nao foi', -2.0]
['mais mal', -3.5]
['nao foram', -2.0]
['nao iriam', -2.0]
['nao seriam', -2.0]
['nao valeriam', -2.0]
['nao produz', -2.0]
['nao surte efeito', -2.0]
['nao faz', -2.0]
['vai ter', 0.2]
['nao vai ter', -2.0]
['nao vai', -2.0]
['pesquisa avancada', 2.0]
['ma fe', -1.5]
['queda de', -1.5]
['acao cai', -1.5]
['acoes caem', -1.5]
['acao sone', 1.5]
['acoes sobem', 1.5]
['acoes desabam', -2.5]	
['acoes despencam', -2.5]	
['acoes sofrem', -2.5]	
['acoes disparam', 2.5]	
['sinal de alerta', -1.5]
['acao contra', -2.5]
['acoes contra', -2.5]
['negam responsabilidade', -2.0]
['nega responsabilidade', -2.0]
['negar responsabilidade', -2.0]
['negam responsabilidades', -2.0]
['nega responsabilidades', -2.0]
['negar responsabilidades', -2.0]
['cobra explicacoes', -2.0]
['cobram explicacoes', -2.0]
['cobrar explicacoes', -2.0]
['notificadas pelo procon', -2.0]
['notificada pelo procon', -2.0]
['notificados pelo procon', -2.0]
['notificado pelo procon', -2.0]
['cobra melhoria', -2.0]
['cobram melhoria', -2.0]
['cobram melhorias', -2.0]
['com descontos', 2.0]
['com desconto', 2.0]
['agiu corretamente', 2.0]
['agir corretamente', 2.0]
['quer barrar', -2.0]
['reclamacoes exigem atencao', -2.0]
['reclamou bastante', -1.5]
['reclamar bastante', -1.5]
['reclamando bastante', -1.5]
['reclamaram bastante', -1.5]
['lideram reclamacoes', -2.5]
['lidera reclamacoes', -2.5]
['lidera reclamacao', -2.5]
['lideram queixas', -2.5]
['lidera queixas', -2.5]
['lidera queixa', -2.5]
['fura fila', -1.0]
['sem autorizacao', -1.0]
['com autorizacao', 1.0]
['suspensão indevida', -2.0]
['autoriza fusao', 1.0]
['piora nos resultados', -2.0]
['abre vagas', 2.0]
['assumir comando', 2.0]
['curso gratuito', 2.0]
['cursos gratuitos', 2.0]
['levar educacao', 2.0]
['impactos positivos', 2.0]
['impacto positivo', 2.0]
['impacto negativo', -2.0]
['impactos negativos', -2.0]
['boletim de ocorrencia', -2.0]
['aumento de', -1.0]
['substancia toxica', -2.0]
['substancias toxicas', -2.0]
['colocar em risco', -2.0]
['colocam em risco', -2.0]
['colocaram em risco', -2.0]
['acao fecha em queda', -2.0]
['nao recomendacao', -2.0]
['nao recomendado', -2.0]
['aplicacoes de risco', -2.0]
['aplicacao de risco', -2.0]
['sujeitas a perdas', -2.0]
['sujeita a perda', -2.0]
['nao garante', -2.0]
['nao garantem', -2.0]
['nao garantiram', -2.0]
['nao garantidas', -2.0]
['fecha em alta', 2.0]
['fecham em alta', 2.0]
['fecha em queda', -2.0]
['fecham em queda', -2.0]
['queda de', -2.0]
['baixas atividades', -2.0]
['baixa atividade', -2.0]
['alta atividade', 2.0]
['altas atividades', 2.0]
['proibe corte positivo', -2.0]
['muito inferior', -2.0]
['muito inferiores', -2.0]
['muito superior', 2.0]
['muito superiores', 2.0]
['pior ja passou', 2.0]
['maior possibilidade', 2.0]
['maiores possibilidades', -1.0]
['mais recomendado', 2.0]
['menos recomendado', -2.0]
['boa aposta', 2.0]
['ma aposta', -2.0]
['boas apostas', 2.0]
['mas apostas', -2.0]